[package]
name = "tucan-plus-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
webdriverbidi = "0.2.2"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
anyhow = "1.0.100"
dotenvy.workspace = true
env_logger.workspace = true
base64 = "0.22.1"
async-trait = "0.1.89"
