[package]
name = "tucan-plus-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
rustenium = { path = "../../../rustenium/rustenium", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
