[package]
name = "html-handler"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.1.2"
rust-version = "1.87"

[dependencies]
scraper.workspace = true
data-encoding.workspace = true
sha3.workspace = true
ego-tree.workspace = true
html5ever.workspace = true
